# Generated by Django 5.2.17 on 2026-08-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_billing_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerbillingprofile',
            name='location_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providerbillingprofile',
            name='revalidation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
