# Generated by Django 5.2.17 on 2026-08-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nemt_trip', '0001_initial_nemt_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, max_length=64, null=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('diagnosis_code', models.CharField(blank=True, max_length=32, null=True)),
                ('place_of_service', models.CharField(blank=True, max_length=16, null=True)),
                ('total_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('DOCUMENTS_REQUIRED', 'Documents required'), ('DOCUMENTS_COMPLETE', 'Documents complete'), ('READY_FOR_837P', 'Ready for 837P'), ('EDI_ACCEPTED', 'EDI accepted'), ('ATTACHMENT_REQUIRED', 'Attachment required'), ('ATTACHMENT_QUEUED', 'Attachment queued'), ('ATTACHMENT_SUBMITTED', 'Attachment submitted'), ('ATTACHMENT_CONFIRMED', 'Attachment confirmed'), ('UNDER_REVIEW', 'Under review'), ('PAID', 'Paid'), ('DENIED', 'Denied')], default='DRAFT', max_length=32, null=True)),
                ('attachment_required', models.BooleanField(default=False)),
                ('attachment_route', models.CharField(blank=True, choices=[('HCPF_APPROVED_CHANNEL', 'HCPF approved channel'), ('HCPF_PORTAL', 'HCPF provider portal'), ('NONE', 'None')], default='NONE', max_length=64, null=True)),
                ('attachment_status', models.CharField(blank=True, choices=[('NOT_REQUIRED', 'Not required'), ('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='nemt_trip.nemttrip')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['status'], name='claim_status_idx'), models.Index(fields=['attachment_required', 'attachment_status'], name='claim_attach_flags_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('claim_number__isnull', False)), fields=('claim_number',), name='uniq_claim_claim_number_not_null'), models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('external_id',), name='uniq_claim_external_id_not_null'), models.UniqueConstraint(condition=models.Q(('trip__isnull', False)), fields=('trip',), name='uniq_claim_trip_not_null')],
            },
        ),
    ]
