# Generated by Django 5.2.17 on 2026-08-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_claimdocument_submissionbatch_batchclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('DOCUMENTS_REQUIRED', 'Documents required'), ('DOCUMENTS_COMPLETE', 'Documents complete'), ('READY_FOR_837P', 'Ready for 837P'), ('EDI_SENT', '837P sent'), ('EDI_ACCEPTED', 'EDI accepted'), ('ATTACHMENT_REQUIRED', 'Attachment required'), ('ATTACHMENT_QUEUED', 'Attachment queued'), ('ATTACHMENT_SUBMITTED', 'Attachment submitted'), ('ATTACHMENT_CONFIRMED', 'Attachment confirmed'), ('UNDER_REVIEW', 'Under review'), ('PAID', 'Paid'), ('DENIED', 'Denied')], default='DRAFT', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='AttachmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, choices=[('HCPF_APPROVED_CHANNEL', 'HCPF approved channel'), ('HCPF_PORTAL', 'HCPF provider portal'), ('NONE', 'None')], default='HCPF_PORTAL', max_length=64, null=True)),
                ('submission_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, choices=[('QUEUED', 'Queued'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='QUEUED', max_length=32, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachment_submissions', to='claim.claim')),
            ],
            options={
                'verbose_name': 'Attachment Submission',
                'verbose_name_plural': 'Attachment Submissions',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['claim', 'status'], name='attach_sub_claim_status_idx'), models.Index(fields=['status', 'is_active'], name='attach_sub_status_active_idx')],
            },
        ),
    ]
