# Generated by Django 5.2.17 on 2026-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('receiver_id', models.CharField(blank=True, max_length=255, null=True)),
                ('environment', models.CharField(choices=[('TEST', 'Test'), ('PRODUCTION', 'Production')], default='TEST', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trading Partner',
                'verbose_name_plural': 'Trading Partners',
                'constraints': [models.UniqueConstraint(fields=('sender_id', 'receiver_id', 'environment'), name='uniq_trading_partner_sender_id_receiver_id_environment')],
            },
        ),
    ]
