# Generated by Django 5.2.17 on 2026-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_partner', '0001_initial_trading_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpartner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='environment',
            field=models.CharField(choices=[('TEST', 'Test'), ('PRODUCTION', 'Production')], db_index=True, default='TEST', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='receiver_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='sender_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='tradingpartner',
            index=models.Index(fields=['environment', 'is_active'], name='tp_env_active_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingpartner',
            index=models.Index(fields=['-created_at'], name='tp_created_at_desc_idx'),
        ),
    ]
