# Generated by Django 5.2.17 on 2026-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_partner', '0002_add_trading_partner_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tradingpartner',
            name='tp_env_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='tradingpartner',
            name='tp_created_at_desc_idx',
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='environment',
            field=models.CharField(choices=[('TEST', 'Test'), ('PRODUCTION', 'Production')], default='TEST', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='receiver_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradingpartner',
            name='sender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
