# Generated by Django 5.2.17 on 2026-08-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_partner', '0003_remove_extra_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpartner',
            name='contact_name',
            field=models.CharField(blank=True, help_text='1000A PER contact name (submitter contact).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tradingpartner',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='1000A PER telephone (digits preferred).', max_length=32, null=True),
        ),
    ]
