from django.urls import path

from apps.claim.attachment_views import (
    AttachmentSubmissionDetailAPIView,
    AttachmentSubmissionListCreateAPIView,
)
from apps.claim.batch_views import (
    BatchClaimDetailAPIView,
    BatchClaimListCreateAPIView,
    SubmissionBatchAddClaimAPIView,
    SubmissionBatchDetailAPIView,
    SubmissionBatchListCreateAPIView,
)
from apps.claim.document_views import (
    ClaimDocumentDetailAPIView,
    ClaimDocumentListCreateAPIView,
    ClaimDocumentStatusAPIView,
)
from apps.claim.pilot_views import LongDistancePilotAPIView
from apps.claim.status_views import (
    ClaimStatusAPIView,
    ClaimValidateAPIView,
    SubmissionBatchStatusAPIView,
)
from apps.claim.workflow_views import (
    AttachmentBulkReviewAPIView,
    AttachmentSubmissionSubmitAPIView,
    ClaimAttachmentDashboardAPIView,
    ClaimAttachmentQueueAPIView,
    ClaimDocumentFileAPIView,
    ClaimDocumentUploadAPIView,
)
from apps.claim.views import (
    ClaimDetailAPIView,
    ClaimFromTripAPIView,
    ClaimListCreateAPIView,
)

urlpatterns = [
    path("claims/", ClaimListCreateAPIView.as_view(), name="claim-list-create"),
    path(
        "claims/attachment-queue/",
        ClaimAttachmentQueueAPIView.as_view(),
        name="claim-attachment-queue",
    ),
    path(
        "claims/attachment-dashboard/",
        ClaimAttachmentDashboardAPIView.as_view(),
        name="claim-attachment-dashboard",
    ),
    path(
        "pilot/long-distance/",
        LongDistancePilotAPIView.as_view(),
        name="pilot-long-distance",
    ),
    path(
        "claims/from-trip/",
        ClaimFromTripAPIView.as_view(),
        name="claim-from-trip",
    ),
    path(
        "claims/<int:pk>/document-status/",
        ClaimDocumentStatusAPIView.as_view(),
        name="claim-document-status",
    ),
    path(
        "claims/<int:pk>/validate/",
        ClaimValidateAPIView.as_view(),
        name="claim-validate",
    ),
    path(
        "claims/<int:pk>/status/",
        ClaimStatusAPIView.as_view(),
        name="claim-status",
    ),
    path("claims/<int:pk>/", ClaimDetailAPIView.as_view(), name="claim-detail"),
    path(
        "claim-documents/upload/",
        ClaimDocumentUploadAPIView.as_view(),
        name="claim-document-upload",
    ),
    path(
        "claim-documents/<int:pk>/file/",
        ClaimDocumentFileAPIView.as_view(),
        name="claim-document-file",
    ),
    path(
        "claim-documents/",
        ClaimDocumentListCreateAPIView.as_view(),
        name="claim-document-list-create",
    ),
    path(
        "claim-documents/<int:pk>/",
        ClaimDocumentDetailAPIView.as_view(),
        name="claim-document-detail",
    ),
    path(
        "attachment-submissions/submit/",
        AttachmentSubmissionSubmitAPIView.as_view(),
        name="attachment-submission-submit",
    ),
    path(
        "attachment-submissions/bulk-review/",
        AttachmentBulkReviewAPIView.as_view(),
        name="attachment-submission-bulk-review",
    ),
    path(
        "attachment-submissions/",
        AttachmentSubmissionListCreateAPIView.as_view(),
        name="attachment-submission-list-create",
    ),
    path(
        "attachment-submissions/<int:pk>/",
        AttachmentSubmissionDetailAPIView.as_view(),
        name="attachment-submission-detail",
    ),
    path(
        "submission-batches/",
        SubmissionBatchListCreateAPIView.as_view(),
        name="submission-batch-list-create",
    ),
    path(
        "submission-batches/<int:pk>/add-claim/",
        SubmissionBatchAddClaimAPIView.as_view(),
        name="submission-batch-add-claim",
    ),
    path(
        "submission-batches/<int:pk>/status/",
        SubmissionBatchStatusAPIView.as_view(),
        name="submission-batch-status",
    ),
    path(
        "submission-batches/<int:pk>/",
        SubmissionBatchDetailAPIView.as_view(),
        name="submission-batch-detail",
    ),
    path(
        "batch-claims/",
        BatchClaimListCreateAPIView.as_view(),
        name="batch-claim-list-create",
    ),
    path(
        "batch-claims/<int:pk>/",
        BatchClaimDetailAPIView.as_view(),
        name="batch-claim-detail",
    ),
]
