# Generated by Django 5.2.17 on 2026-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_claimdocument_submissionbatch_batchclaim'),
        ('edi', '0003_edifiletransferlog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='edicontrolnumber',
            name='uniq_active_isa13_per_environment',
        ),
        migrations.AddConstraint(
            model_name='edicontrolnumber',
            constraint=models.UniqueConstraint(condition=models.Q(('environment__isnull', False), ('is_active', True), ('isa13__isnull', False)), fields=('environment', 'isa13'), name='uniq_active_isa13_per_environment'),
        ),
    ]
