# Generated by Django 5.2.17 on 2026-08-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_edi_ack_and_attachment_submission'),
        ('edi', '0004_edicontrolnumber_isa13_constraint_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDIAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ack_type', models.CharField(choices=[('999', 'Implementation Acknowledgment'), ('277', 'Claim Status'), ('OTHER', 'Other')], default='999', max_length=16)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PARTIAL', 'Partial'), ('ERROR', 'Error')], default='ACCEPTED', max_length=32)),
                ('affected_st02', models.CharField(blank=True, help_text='Transaction set control number (ST02) affected by this ack.', max_length=16, null=True)),
                ('raw_file_ref', models.CharField(blank=True, max_length=1024, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edi_acknowledgements', to='claim.submissionbatch')),
                ('edi_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledgements', to='edi.edifile')),
            ],
            options={
                'verbose_name': 'EDI Acknowledgement',
                'verbose_name_plural': 'EDI Acknowledgements',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['batch', 'ack_type'], name='edi_ack_batch_type_idx'), models.Index(fields=['status', 'is_active'], name='edi_ack_status_active_idx'), models.Index(fields=['affected_st02'], name='edi_ack_st02_idx')],
            },
        ),
    ]
