# Generated by Django 5.2.17 on 2026-08-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_edi_ack_and_attachment_submission'),
        ('edi', '0005_edi_ack_and_attachment_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDI999Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('remote_path', models.CharField(max_length=1024)),
                ('file_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('QUEUED', 'Queued'), ('DOWNLOADING', 'Downloading'), ('PARSING', 'Parsing'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='DISCOVERED', max_length=32)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledgement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='edi.ediacknowledgement')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_999_imports', to='claim.submissionbatch')),
                ('credentials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edi_999_imports', to='edi.sftpcredentials')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_999_imports', to='edi.sftpdirectory')),
                ('edi_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_999_imports', to='edi.edifile')),
            ],
            options={
                'verbose_name': 'EDI 999 Import',
                'verbose_name_plural': 'EDI 999 Imports',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['status', 'is_active'], name='edi_999_imp_status_active_idx'), models.Index(fields=['file_hash'], name='edi_999_imp_hash_idx'), models.Index(fields=['filename'], name='edi_999_imp_filename_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('credentials__isnull', False), ('is_active', True), ('remote_path__isnull', False)), fields=('credentials', 'remote_path'), name='uniq_active_edi_999_import_remote_path')],
            },
        ),
    ]
