# Generated by Django 5.2.17 on 2026-09-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_claimdocument_service_and_verification_dates'),
        ('edi', '0010_edi_validation_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDI277Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('remote_path', models.CharField(max_length=1024)),
                ('file_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('QUEUED', 'Queued'), ('DOWNLOADING', 'Downloading'), ('PARSING', 'Parsing'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='DISCOVERED', max_length=32)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'EDI 277 Import',
                'verbose_name_plural': 'EDI 277 Imports',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='edi835import',
            name='uniq_active_edi_835_import_remote_path',
        ),
        migrations.AlterField(
            model_name='edifile',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('837P', '837 Professional'), ('999', 'Implementation Acknowledgment'), ('277', 'Claim Status'), ('835', 'Payment / Remittance Advice'), ('OTHER', 'Other')], default='837P', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='sftpdirectory',
            name='purpose',
            field=models.CharField(choices=[('OUTBOUND_837P', 'Outbound 837P'), ('OUTBOUND_ATTACHMENT', 'Outbound attachments'), ('INBOUND_999', 'Inbound 999'), ('INBOUND_277', 'Inbound 277'), ('INBOUND_835', 'Inbound 835'), ('GENERAL', 'General send/receive')], default='GENERAL', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='edi835import',
            constraint=models.UniqueConstraint(condition=models.Q(('credentials__isnull', False), ('is_active', True), ('remote_path__isnull', False)), fields=('credentials', 'remote_path'), name='uniq_active_edi_835_import_remote_path'),
        ),
        migrations.AddField(
            model_name='edi277import',
            name='acknowledgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_277_rows', to='edi.ediacknowledgement'),
        ),
        migrations.AddField(
            model_name='edi277import',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_277_imports', to='claim.submissionbatch'),
        ),
        migrations.AddField(
            model_name='edi277import',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edi_277_imports', to='edi.sftpcredentials'),
        ),
        migrations.AddField(
            model_name='edi277import',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_277_imports', to='edi.sftpdirectory'),
        ),
        migrations.AddField(
            model_name='edi277import',
            name='edi_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edi_277_imports', to='edi.edifile'),
        ),
        migrations.AddIndex(
            model_name='edi277import',
            index=models.Index(fields=['status', 'is_active'], name='edi_277_imp_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='edi277import',
            index=models.Index(fields=['file_hash'], name='edi_277_imp_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='edi277import',
            index=models.Index(fields=['filename'], name='edi_277_imp_filename_idx'),
        ),
        migrations.AddConstraint(
            model_name='edi277import',
            constraint=models.UniqueConstraint(condition=models.Q(('credentials__isnull', False), ('is_active', True), ('remote_path__isnull', False)), fields=('credentials', 'remote_path'), name='uniq_active_edi_277_import_remote_path'),
        ),
    ]
