# Generated by Django 5.2.17 on 2026-08-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongDistanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('DESIGNATED_RURAL', 'Designated rural')], max_length=32, null=True)),
                ('review_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('verification_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Long Distance Rule',
                'verbose_name_plural': 'Long Distance Rules',
                'constraints': [models.UniqueConstraint(fields=('county_type',), name='uniq_long_distance_rule_county_type')],
            },
        ),
    ]
