# Generated by Django 5.2.17 on 2026-08-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial_patient'),
        ('provider_billing_profile', '0002_providerbillingprofile_location_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NemtTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('pickup', models.CharField(blank=True, max_length=500, null=True)),
                ('dropoff', models.CharField(blank=True, max_length=500, null=True)),
                ('one_way_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage_units', models.PositiveIntegerField(blank=True, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nemt_trips', to='patient.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nemt_trips', to='provider_billing_profile.providerbillingprofile')),
            ],
            options={
                'verbose_name': 'NEMT Trip',
                'verbose_name_plural': 'NEMT Trips',
                'ordering': ('-service_date', '-id'),
            },
        ),
    ]
