# Generated by Django 5.2.17 on 2026-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemt_trip', '0001_initial_nemt_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='nemttrip',
            name='driver_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nemttrip',
            name='driver_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
