# Generated by Django 5.2.17 on 2026-08-30 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_code', models.CharField(blank=True, max_length=32, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('units', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='claim.claim')),
            ],
            options={
                'verbose_name': 'Claim Service Line',
                'verbose_name_plural': 'Claim Service Lines',
                'ordering': ('claim_id', 'id'),
                'indexes': [models.Index(fields=['claim', 'procedure_code'], name='csl_claim_proc_idx')],
            },
        ),
    ]
